import { Jost } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/layout/Navbar";
import Footer from "@/Components/layout/Footer";
import { ToastContainer } from "react-toastify";
import NextAuthProvider from "@/provider/NextAuthProvider";
import { CartProvider } from "@/provider/CartProvider";

const jost = Jost({
  weight: ["400", "500", "600", "700"],
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <NextAuthProvider>
      <CartProvider>
        <html lang="en" suppressHydrationWarning>
          <body
            className={`${jost.className} antialiased`}
            suppressHydrationWarning
          >
            <header>
              <Navbar />
            </header>
            <main className="py-2 md:w-11/12 mx-auto min-h-[calc(100vh-302px)]">
              {children}
            </main>
            <footer>
              <Footer />
            </footer>
            <ToastContainer />
          </body>
        </html>
      </CartProvider>
    </NextAuthProvider>
  );
}
